CREATE TABLE IF NOT EXISTS public."Pharmacies"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "Address" text COLLATE pg_catalog."default",
    "ContactInfo" text COLLATE pg_catalog."default",
    "City" text COLLATE pg_catalog."default",
    "State" text COLLATE pg_catalog."default",
    "ZipCode" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Pharmacies" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Pharmacies"
    OWNER to pratyushad;
