CREATE TABLE IF NOT EXISTS public."Medicines"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "StockQuantity" integer NOT NULL,
    "Price" numeric NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Medicines" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Medicines"
    OWNER to pratyushad;
