CREATE TABLE IF NOT EXISTS public."EmergencyContacts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default",
    "ContactName" text COLLATE pg_catalog."default",
    "Relation" text COLLATE pg_catalog."default",
    "MobileNumber" text COLLATE pg_catalog."default",
    "Address" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_EmergencyContacts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmergencyContacts_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."EmergencyContacts"
    OWNER to pratyushad;

-- Index: public.IX_EmergencyContacts_UserId
CREATE INDEX IF NOT EXISTS "IX_EmergencyContacts_UserId"
    ON public."EmergencyContacts" USING btree
    ("""UserId""" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;