CREATE TABLE IF NOT EXISTS public."Feedbacks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "AppointmentId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "FeedbackText" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Feedbacks_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId")
        REFERENCES public."Appointments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Feedbacks_Doctors_DoctorId" FOREIGN KEY ("DoctorId")
        REFERENCES public."Doctors" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Feedbacks_Patients_PatientId" FOREIGN KEY ("PatientId")
        REFERENCES public."Patients" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE public."Feedbacks"
    OWNER to pratyushad;

-- Index: public.IX_Feedbacks_AppointmentId
CREATE INDEX IF NOT EXISTS "IX_Feedbacks_AppointmentId"
    ON public."Feedbacks" USING btree
    ("""AppointmentId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Feedbacks_DoctorId
CREATE INDEX IF NOT EXISTS "IX_Feedbacks_DoctorId"
    ON public."Feedbacks" USING btree
    ("""DoctorId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Feedbacks_PatientId
CREATE INDEX IF NOT EXISTS "IX_Feedbacks_PatientId"
    ON public."Feedbacks" USING btree
    ("""PatientId""" ASC NULLS LAST)
    TABLESPACE pg_default;