CREATE TABLE IF NOT EXISTS public."DoctorAvailabilities"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DoctorId" integer NOT NULL,
    "DayOfWeek" text COLLATE pg_catalog."default",
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "Date" date NOT NULL DEFAULT '-infinity'::date,
    CONSTRAINT "PK_DoctorAvailabilities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DoctorAvailabilities_Doctors_DoctorId" FOREIGN KEY ("DoctorId")
        REFERENCES public."Doctors" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."DoctorAvailabilities"
    OWNER to pratyushad;

-- Index: public.IX_DoctorAvailabilities_DoctorId
CREATE INDEX IF NOT EXISTS "IX_DoctorAvailabilities_DoctorId"
    ON public."DoctorAvailabilities" USING btree
    ("""DoctorId""" ASC NULLS LAST)
    TABLESPACE pg_default;