CREATE TABLE IF NOT EXISTS public."Appointments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Date" timestamp with time zone NOT NULL,
    "Time" interval NOT NULL,
    "Reason" text COLLATE pg_catalog."default",
    "OtherReason" text COLLATE pg_catalog."default",
    "Symptoms" text COLLATE pg_catalog."default",
    "Status" text COLLATE pg_catalog."default",
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "Mode" text COLLATE pg_catalog."default",
    "OnlineMeetingLink" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId")
        REFERENCES public."Doctors" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId")
        REFERENCES public."Patients" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."Appointments"
    OWNER to pratyushad;

-- Index: public.IX_Appointments_DoctorId
CREATE INDEX IF NOT EXISTS "IX_Appointments_DoctorId"
    ON public."Appointments" USING btree
    ("""DoctorId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Appointments_PatientId
CREATE INDEX IF NOT EXISTS "IX_Appointments_PatientId"
    ON public."Appointments" USING btree
    ("""PatientId""" ASC NULLS LAST)
    TABLESPACE pg_default;