CREATE TABLE IF NOT EXISTS public."Patients"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default",
    "MedicalHistory" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Patients_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Patients"
    OWNER to pratyushad;

-- Index: public.IX_Patients_UserId
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Patients_UserId"
    ON public."Patients" USING btree
    ("""UserId""" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;