CREATE TABLE IF NOT EXISTS public."DoctorValidations"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FirstName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "LastName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "LicenseNumber" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_DoctorValidations" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."DoctorValidations"
    OWNER to pratyushad;

-- Index: public.IX_DoctorValidations_LicenseNumber
CREATE UNIQUE INDEX IF NOT EXISTS "IX_DoctorValidations_LicenseNumber"
    ON public."DoctorValidations" USING btree
    ("""LicenseNumber""" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;