CREATE TABLE IF NOT EXISTS public."DoctorHolidays"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DoctorId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DoctorHolidays" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DoctorHolidays_Doctors_DoctorId" FOREIGN KEY ("DoctorId")
        REFERENCES public."Doctors" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."DoctorHolidays"
    OWNER to pratyushad;

-- Index: public.IX_DoctorHolidays_DoctorId
CREATE INDEX IF NOT EXISTS "IX_DoctorHolidays_DoctorId"
    ON public."DoctorHolidays" USING btree
    ("""DoctorId""" ASC NULLS LAST)
    TABLESPACE pg_default;