CREATE TABLE IF NOT EXISTS public."Orders"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "PrescriptionId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "MedicineId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "TotalPrice" numeric NOT NULL,
    "PaymentStatus" text COLLATE pg_catalog."default",
    "SessionId" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Medicines_MedicineId" FOREIGN KEY ("MedicineId")
        REFERENCES public."Medicines" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Patients_PatientId" FOREIGN KEY ("PatientId")
        REFERENCES public."Patients" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Prescriptions_PrescriptionId" FOREIGN KEY ("PrescriptionId")
        REFERENCES public."Prescriptions" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."Orders"
    OWNER to pratyushad;

-- Index: public.IX_Orders_MedicineId
CREATE INDEX IF NOT EXISTS "IX_Orders_MedicineId"
    ON public."Orders" USING btree
    ("""MedicineId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Orders_PatientId
CREATE INDEX IF NOT EXISTS "IX_Orders_PatientId"
    ON public."Orders" USING btree
    ("""PatientId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Orders_PrescriptionId
CREATE INDEX IF NOT EXISTS "IX_Orders_PrescriptionId"
    ON public."Orders" USING btree
    ("""PrescriptionId""" ASC NULLS LAST)
    TABLESPACE pg_default;