CREATE TABLE IF NOT EXISTS public."Prescriptions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DoctorId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "MedicineName" text COLLATE pg_catalog."default",
    "Dosage" text COLLATE pg_catalog."default",
    "Duration" text COLLATE pg_catalog."default",
    "PharmacyId" integer,
    "IsCollected" boolean NOT NULL,
    CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prescriptions_Doctors_DoctorId" FOREIGN KEY ("DoctorId")
        REFERENCES public."Doctors" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Prescriptions_Patients_PatientId" FOREIGN KEY ("PatientId")
        REFERENCES public."Patients" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Prescriptions_Pharmacies_PharmacyId" FOREIGN KEY ("PharmacyId")
        REFERENCES public."Pharmacies" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Prescriptions"
    OWNER to pratyushad;

-- Index: public.IX_Prescriptions_DoctorId
CREATE INDEX IF NOT EXISTS "IX_Prescriptions_DoctorId"
    ON public."Prescriptions" USING btree
    ("""DoctorId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Prescriptions_PatientId
CREATE INDEX IF NOT EXISTS "IX_Prescriptions_PatientId"
    ON public."Prescriptions" USING btree
    ("""PatientId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Prescriptions_PharmacyId
CREATE INDEX IF NOT EXISTS "IX_Prescriptions_PharmacyId"
    ON public."Prescriptions" USING btree
    ("""PharmacyId""" ASC NULLS LAST)
    TABLESPACE pg_default;