CREATE TABLE IF NOT EXISTS public."Doctors"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default",
    "Specialization" text COLLATE pg_catalog."default",
    "YearsOfExperience" integer DEFAULT 0,
    "Education" text COLLATE pg_catalog."default",
    "LicenseNumber" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Doctors"
    OWNER to pratyushad;

-- Index: public.IX_Doctors_UserId
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Doctors_UserId"
    ON public."Doctors" USING btree
    ("""UserId""" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;